#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name:  Bluetooth LE Tracking

# Short bio or description (displayed in the header)
description: Active 2.4 GHz RFID tracking

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: images/logo.png

#
# Flags below are optional
#
github_url: https://github.com/meriac/openbeacon-ng

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: contact@openbeacon.org
  facebook: 
  flickr: 
  github: meriac/openbeacon-ng
  instagram: 
  linkedin: OpenBeacon.org
  flattr: OpenBeacon
  pinterest: 
  rss: enable
  twitter: FoolsDelight
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-55402589-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://www.openbeacon.org

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

kramdown:
  input: GFM

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from # support redirects

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
